-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE nestio TO nestio;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nestio;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO nestio;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO nestio;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO nestio;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO nestio;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO nestio; 