CREATE TABLE IF NOT EXISTS "NYCMapPLUTO" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"bbl" varchar(20) NOT NULL,
	"borough" varchar(10) NOT NULL,
	"block" varchar(10) NOT NULL,
	"lot" varchar(10) NOT NULL,
	"borocode" varchar(5),
	"address" text,
	"bldgclass" varchar(10),
	"landuse" varchar(10),
	"ownername" text,
	"lotarea" varchar(20),
	"bldgarea" varchar(20),
	"comarea" varchar(20),
	"resarea" varchar(20),
	"officearea" varchar(20),
	"retailarea" varchar(20),
	"garagearea" varchar(20),
	"strgearea" varchar(20),
	"factryarea" varchar(20),
	"otherarea" varchar(20),
	"numbldgs" varchar(10),
	"numfloors" varchar(20),
	"unitsres" varchar(10),
	"unitstotal" varchar(10),
	"lotfront" varchar(20),
	"lotdepth" varchar(20),
	"bldgfront" varchar(20),
	"bldgdepth" varchar(20),
	"assessland" varchar(20),
	"assesstot" varchar(20),
	"exempttot" varchar(20),
	"yearbuilt" varchar(10),
	"yearalter1" varchar(10),
	"yearalter2" varchar(10),
	"builtfar" varchar(20),
	"residfar" varchar(20),
	"commfar" varchar(20),
	"facilfar" varchar(20),
	"cd" varchar(10),
	"ct2010" varchar(20),
	"cb2010" varchar(20),
	"schooldist" varchar(10),
	"council" varchar(10),
	"zipcode" varchar(10),
	"firecomp" varchar(20),
	"policeprct" varchar(10),
	"healtharea" varchar(10),
	"sanitboro" varchar(10),
	"sanitsub" varchar(10),
	"zonedist1" varchar(20),
	"overlay1" varchar(20),
	"splitzone" boolean,
	"zonemap" varchar(20),
	"areasource" varchar(5),
	"ext" varchar(5),
	"proxcode" varchar(5),
	"irrlotcode" boolean,
	"lottype" varchar(5),
	"bsmtcode" varchar(5),
	"latitude" varchar(20),
	"longitude" varchar(20),
	"xcoord" varchar(20),
	"ycoord" varchar(20),
	"tract2010" varchar(20),
	"sanborn" varchar(20),
	"taxmap" varchar(20),
	"plutomapid" varchar(10),
	"version" varchar(10),
	"bct2020" varchar(20),
	"bctcb2020" varchar(20),
	"sanitdistrict" varchar(10),
	"healthcenterdistrict" varchar(10),
	"easements" varchar(10),
	"geojsonDataId" uuid,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "NYCMapPLUTO_bbl_unique" UNIQUE("bbl")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "NYCMapPLUTO" ADD CONSTRAINT "NYCMapPLUTO_geojsonDataId_GeoJSONData_id_fk" FOREIGN KEY ("geojsonDataId") REFERENCES "public"."GeoJSONData"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
